pokemon_categories = {
    "fossil": [
        "omanyte",
        "omastar",
        "kabuto",
        "kabutops",
        "aerodactyl",
    ],
    "legendary": [
        "articuno",
        "zapdos",
        "moltres",
        "mewtwo",
        "mew",
    ],
    "safari": [
        "nidoran-m",
        "nidorino",
        "nidoran-f",
        "nidorina",
        "exeggcute",
        "rhyhorn",
        "venonat",
        "venomoth",
        "paras",
        "parasect",
        "scyther",
        "pinsir",
        "chansey",
        "kangaskhan",
        "lickitung",
        "tauros",
        "tangela",
        "magikarp",
        "poliwag",
        "goldeen",
        "psyduck",
        "slowpoke",
        "krabby",
        "dratini",
        "dragonair",
        "doduo",
        "cubone",
        "marowak",
    ],
}